// ── DATA ──
const JOBS = [
  { id:'uber',      name:'Uber / Lyft',     count:38, icon:'user' },
  { id:'doordash',  name:'DoorDash',         count:34, icon:'bag' },
  { id:'airbnb',    name:'Airbnb Host',      count:41, icon:'home' },
  { id:'onlyfans',  name:'OnlyFans',         count:44, icon:'doc' },
  { id:'etsy',      name:'Etsy Seller',      count:36, icon:'star' },
  { id:'instacart', name:'Instacart',        count:32, icon:'plus' },
  { id:'freelancer',name:'Upwork / Fiverr',  count:29, icon:'screen' },
  { id:'amazon',    name:'Amazon Flex',      count:33, icon:'truck' },
  { id:'turo',      name:'Turo Host',        count:28, icon:'clock' },
  { id:'youtube',   name:'Twitch / YouTube', count:37, icon:'video' },
  { id:'aifreelancer',name:'AI Freelancer',  count:31, icon:'circle' },
  { id:'rover',     name:'Rover / Wag',      count:26, icon:'paw' },
  { id:'photo',     name:'Photographer',     count:39, icon:'user' },
  { id:'taskrabbit',name:'TaskRabbit',       count:27, icon:'store' },
];

const ICONS = {
  user: '<circle cx="10" cy="10" r="8"/><path d="M6 13c0-2.2 1.8-4 4-4s4 1.8 4 4"/><circle cx="10" cy="7.5" r="1.5"/>',
  bag:  '<rect x="3" y="6" width="14" height="10" rx="1.5"/><path d="M7 6V5a3 3 0 016 0v1"/><path d="M10 11v2"/>',
  home: '<path d="M3 8l7-5 7 5v9a1 1 0 01-1 1H4a1 1 0 01-1-1V8z"/><path d="M8 17v-6h4v6"/>',
  doc:  '<rect x="4" y="3" width="12" height="15" rx="2"/><path d="M8 7h4M8 10h4M8 13h2"/>',
  star: '<path d="M10 3l1.5 4.5H16l-3.7 2.7 1.4 4.3L10 12l-3.7 2.5 1.4-4.3L4 7.5h4.5L10 3z"/>',
  plus: '<circle cx="10" cy="10" r="7"/><path d="M7 10h6M10 7v6"/>',
  screen:'<rect x="3" y="4" width="14" height="10" rx="1.5"/><path d="M7 17h6M10 14v3"/>',
  truck: '<path d="M4 14l3-8h6l3 8"/><path d="M2 14h16"/><path d="M10 6V4"/>',
  clock: '<circle cx="10" cy="10" r="7"/><path d="M10 6v4l3 2"/>',
  video: '<path d="M3 5h14v9a1 1 0 01-1 1H4a1 1 0 01-1-1V5z"/><path d="M7 17h6"/><circle cx="10" cy="10" r="2.5"/>',
  circle:'<path d="M5 10h10M10 5v10"/><circle cx="10" cy="10" r="7"/>',
  paw:   '<path d="M10 3c-3.9 0-7 2-7 6 0 2.5 1.2 4 2 5h10c.8-1 2-2.5 2-5 0-4-3.1-6-7-6z"/><path d="M8 17h4"/>',
  store: '<path d="M5 3h10l2 5H3L5 3z"/><rect x="3" y="8" width="14" height="9" rx="1"/><path d="M10 11v4"/>',
};

const DEDUCTIONS = {
  uber: {
    title: 'Uber / Lyft Driver', sub: '38 deductions available ” most drivers claim only 3“4',
    totalMin: 6400, totalMax: 18000,
    items: [
      { name:'Business Mileage', note:'Standard or actual expense method', rate:'70•/mile (IRS 2026)', saveMin:3200, saveMax:8400, p:'high' },
      { name:'SE Tax Deduction', note:'Deduct 50% of self-employment tax', rate:'7.65% of net earnings', saveMin:900, saveMax:3100, p:'high' },
      { name:'Health Insurance Premium', note:'If not eligible for employer coverage', rate:'100% deductible', saveMin:2400, saveMax:6000, p:'high' },
      { name:'Cell Phone Bill', note:'Proportional to business use (50“80%)', rate:'50“80% of monthly bill', saveMin:480, saveMax:960, p:'high' },
      { name:'Car Insurance', note:'Proportional to business miles / total miles', rate:'Business-use %', saveMin:400, saveMax:1200, p:'med' },
      { name:'Toll Fees (during rides)', note:'Keep records per trip', rate:'100% deductible', saveMin:200, saveMax:800, p:'med' },
      { name:'Car Washes', note:'For vehicles used exclusively for rideshare', rate:'100% deductible', saveMin:100, saveMax:400, p:'med' },
      { name:'Phone Mount / Accessories', note:'GPS holder, charger, dashcam', rate:'100% deductible', saveMin:50, saveMax:200, p:'med' },
      { name:'Roadside Assistance (AAA)', note:'Only business-use portion', rate:'Business-use %', saveMin:50, saveMax:150, p:'med' },
      { name:'Tax Preparation Software', note:'TaxAct, Keeper, TurboTax', rate:'100% deductible', saveMin:50, saveMax:150, p:'med' },
    ]
  },
  doordash: {
    title: 'DoorDash / UberEats Driver', sub: '34 deductions available',
    totalMin: 5800, totalMax: 14000,
    items: [
      { name:'Business Mileage', note:'From app open to last delivery drop-off', rate:'70•/mile (IRS 2026)', saveMin:2800, saveMax:7200, p:'high' },
      { name:'SE Tax Deduction', note:'Deduct 50% of self-employment tax', rate:'7.65% of net earnings', saveMin:800, saveMax:2800, p:'high' },
      { name:'Insulated Delivery Bags', note:'Hot bags, pizza bags, drink carriers', rate:'100% deductible', saveMin:50, saveMax:200, p:'high' },
      { name:'Cell Phone Bill', note:'70“80% if used primarily for deliveries', rate:'70“80% of bill', saveMin:480, saveMax:960, p:'high' },
      { name:'Health Insurance Premium', note:'Self-employed health insurance deduction', rate:'100% deductible', saveMin:2400, saveMax:6000, p:'high' },
      { name:'Toll Fees', note:'Keep receipts per delivery run', rate:'100% deductible', saveMin:150, saveMax:600, p:'med' },
      { name:'Car Washes', note:'For delivery vehicle maintenance', rate:'100% deductible', saveMin:100, saveMax:350, p:'med' },
      { name:'Parking Fees', note:'At restaurants and delivery locations', rate:'100% deductible', saveMin:100, saveMax:400, p:'med' },
      { name:'Car Insurance (business %)', note:'Miles driven for DoorDash / total miles', rate:'Business-use %', saveMin:300, saveMax:900, p:'med' },
      { name:'Tax Software', note:'Cost of filing software is deductible', rate:'100% deductible', saveMin:50, saveMax:150, p:'med' },
    ]
  },
  airbnb: {
    title: 'Airbnb Host', sub: '41 deductions available ” short-term rental is highly deductible',
    totalMin: 8200, totalMax: 22000,
    items: [
      { name:'Depreciation (Schedule E)', note:'Residential property depreciated over 27.5 years', rate:'Cost basis ÷ 27.5', saveMin:3000, saveMax:12000, p:'high' },
      { name:'Mortgage Interest', note:'Proportional to rental-use days / total days', rate:'Rental-use %', saveMin:2000, saveMax:8000, p:'high' },
      { name:'Cleaning & Laundry', note:'Professional cleaning between guests', rate:'100% deductible', saveMin:600, saveMax:3000, p:'high' },
      { name:'Platform Fees (Airbnb)', note:'Airbnb service fees deducted from your payouts', rate:'100% deductible', saveMin:400, saveMax:2000, p:'high' },
      { name:'Supplies & Amenities', note:'Toiletries, coffee, linens, towels', rate:'100% deductible', saveMin:300, saveMax:1500, p:'high' },
      { name:'Utilities (rental-use portion)', note:'Electricity, water, gas, internet', rate:'Rental-use %', saveMin:500, saveMax:2400, p:'high' },
      { name:'Property Management Software', note:'Hostfully, Guesty, PriceLabs', rate:'100% deductible', saveMin:100, saveMax:500, p:'med' },
      { name:'Home Insurance (rental %)', note:'Rental days / total days used', rate:'Rental-use %', saveMin:200, saveMax:800, p:'med' },
      { name:'Repairs & Maintenance', note:'Only for issues in rental space', rate:'100% deductible', saveMin:200, saveMax:2000, p:'med' },
      { name:'Photography for Listing', note:'Professional photos for your listing', rate:'100% deductible', saveMin:100, saveMax:400, p:'med' },
    ]
  },
  onlyfans: {
    title: 'OnlyFans Creator', sub: '44 deductions available ” creators often miss 60% of their write-offs',
    totalMin: 7100, totalMax: 18000,
    items: [
      { name:'Camera & Photography Equipment', note:'DSLR, mirrorless, ring lights, tripods', rate:'100% (or depreciated)', saveMin:500, saveMax:3000, p:'high' },
      { name:'Home Office Deduction', note:'Dedicated shooting/editing space at home', rate:'$5/sq ft up to 300 sq ft', saveMin:750, saveMax:1500, p:'high' },
      { name:'SE Tax Deduction', note:'50% of self-employment tax is deductible', rate:'7.65% of net earnings', saveMin:1000, saveMax:3500, p:'high' },
      { name:'Internet (business %)', note:'Used for streaming and content upload', rate:'80“100% of bill', saveMin:500, saveMax:1200, p:'high' },
      { name:'Costumes & Props', note:'Used exclusively for content creation', rate:'100% deductible', saveMin:300, saveMax:2000, p:'high' },
      { name:'OnlyFans Platform Fees', note:'20% taken by OnlyFans is deductible', rate:'20% of gross revenue', saveMin:1000, saveMax:8000, p:'high' },
      { name:'Editing Software', note:'Adobe Premiere, Final Cut Pro, Lightroom', rate:'100% deductible', saveMin:200, saveMax:800, p:'med' },
      { name:'Health Insurance Premium', note:'Self-employed health insurance deduction', rate:'100% deductible', saveMin:2400, saveMax:6000, p:'med' },
      { name:'Background / Studio Décor', note:'Used exclusively for filming', rate:'100% deductible', saveMin:200, saveMax:1000, p:'med' },
      { name:'Cell Phone (business %)', note:'Used for content creation and communication', rate:'60“80% of bill', saveMin:400, saveMax:960, p:'med' },
    ]
  },
  etsy: {
    title: 'Etsy Seller', sub: '36 deductions available ” materials, studio, shipping, fees',
    totalMin: 4900, totalMax: 12000,
    items: [
      { name:'Cost of Goods Sold (Materials)', note:'Raw materials used in products you sold', rate:'100% deductible (Schedule C, Part III)', saveMin:1000, saveMax:8000, p:'high' },
      { name:'Etsy Platform Fees', note:'Listing fees, transaction fees, Ads', rate:'100% deductible', saveMin:400, saveMax:2000, p:'high' },
      { name:'Shipping & Postage', note:'All postage, packing materials, labels', rate:'100% deductible', saveMin:300, saveMax:1500, p:'high' },
      { name:'SE Tax Deduction', note:'50% of SE tax is deductible on Schedule 1', rate:'7.65% of net earnings', saveMin:600, saveMax:2200, p:'high' },
      { name:'Home Studio / Office', note:'Dedicated craft room used exclusively for Etsy', rate:'$5/sq ft up to 300 sq ft', saveMin:750, saveMax:1500, p:'high' },
      { name:'Packaging Supplies', note:'Boxes, tissue paper, ribbon, tape', rate:'100% deductible', saveMin:100, saveMax:600, p:'med' },
      { name:'Photography Equipment', note:'For product photography', rate:'100% deductible', saveMin:100, saveMax:500, p:'med' },
      { name:'Design Software', note:'Canva Pro, Adobe, Procreate', rate:'100% deductible', saveMin:100, saveMax:600, p:'med' },
      { name:'Health Insurance Premium', note:'If self-employed, deduct 100%', rate:'100% deductible', saveMin:2400, saveMax:6000, p:'med' },
      { name:'Mileage (post office trips)', note:'Driving to mail packages ” 70•/mile', rate:'70•/mile', saveMin:50, saveMax:300, p:'med' },
    ]
  },
  instacart: {
    title: 'Instacart Shopper', sub: '32 deductions available',
    totalMin: 4200, totalMax: 10000,
    items: [
      { name:'Business Mileage', note:'Driving to stores and to customers', rate:'70•/mile (IRS 2026)', saveMin:2000, saveMax:5500, p:'high' },
      { name:'SE Tax Deduction', note:'50% of self-employment tax', rate:'7.65% of net earnings', saveMin:600, saveMax:2000, p:'high' },
      { name:'Insulated Grocery Bags', note:'Reusable cold bags for deliveries', rate:'100% deductible', saveMin:30, saveMax:100, p:'high' },
      { name:'Cell Phone Bill', note:'Used for the Instacart app and navigation', rate:'60“80% of bill', saveMin:400, saveMax:960, p:'high' },
      { name:'Health Insurance Premium', note:'Self-employed deduction', rate:'100% deductible', saveMin:2400, saveMax:6000, p:'high' },
      { name:'Car Insurance (business %)', note:'Miles shopped / total miles', rate:'Business-use %', saveMin:300, saveMax:900, p:'med' },
      { name:'Toll Fees', note:'Tolls paid during shopping/delivery runs', rate:'100% deductible', saveMin:100, saveMax:400, p:'med' },
      { name:'Parking Fees', note:'At store parking if paid', rate:'100% deductible', saveMin:50, saveMax:300, p:'med' },
      { name:'Tax Software', note:'Filing software is 100% deductible', rate:'100% deductible', saveMin:50, saveMax:150, p:'med' },
      { name:'Car Washes', note:'For delivery vehicle', rate:'100% deductible', saveMin:100, saveMax:350, p:'med' },
    ]
  },
  freelancer: {
    title: 'Upwork / Fiverr Freelancer', sub: '29 deductions available ” digital freelancers miss most of these',
    totalMin: 5600, totalMax: 14000,
    items: [
      { name:'Home Office Deduction', note:'Dedicated workspace used only for work', rate:'$5/sq ft up to 300 sq ft', saveMin:750, saveMax:1500, p:'high' },
      { name:'SE Tax Deduction', note:'50% of self-employment tax', rate:'7.65% of net earnings', saveMin:1000, saveMax:3500, p:'high' },
      { name:'Internet Bill', note:'Business-use percentage of monthly internet', rate:'80“100% if mainly for work', saveMin:600, saveMax:1200, p:'high' },
      { name:'Platform Fees', note:'Upwork service fees (5“20%), Fiverr 20%', rate:'100% deductible', saveMin:500, saveMax:3000, p:'high' },
      { name:'Health Insurance Premium', note:'Self-employed health insurance deduction', rate:'100% deductible', saveMin:2400, saveMax:6000, p:'high' },
      { name:'Software Subscriptions', note:'Adobe, Figma, Slack, GitHub, Notion, etc.', rate:'100% deductible', saveMin:300, saveMax:1200, p:'med' },
      { name:'Computer & Equipment', note:'Depreciated or Section 179 expensing', rate:'100% (Section 179)', saveMin:300, saveMax:2000, p:'med' },
      { name:'Education & Courses', note:'Online courses directly related to your work', rate:'100% deductible', saveMin:100, saveMax:800, p:'med' },
      { name:'Cell Phone (business %)', note:'For client communication and work calls', rate:'50“70% of bill', saveMin:300, saveMax:840, p:'med' },
      { name:'Professional Books / Resources', note:'Industry books, research subscriptions', rate:'100% deductible', saveMin:50, saveMax:300, p:'med' },
    ]
  },
  amazon: {
    title: 'Amazon Flex Driver', sub: '33 deductions available',
    totalMin: 4800, totalMax: 11000,
    items: [
      { name:'Business Mileage', note:'From when you leave your home to final drop-off', rate:'70•/mile (IRS 2026)', saveMin:2500, saveMax:6500, p:'high' },
      { name:'SE Tax Deduction', note:'50% of self-employment tax', rate:'7.65% of net earnings', saveMin:700, saveMax:2400, p:'high' },
      { name:'Cell Phone Bill', note:'Used for the Amazon Flex app', rate:'70“80% of bill', saveMin:480, saveMax:960, p:'high' },
      { name:'Health Insurance Premium', note:'Self-employed health insurance', rate:'100% deductible', saveMin:2400, saveMax:6000, p:'high' },
      { name:'Car Insurance (business %)', note:'Business miles / total miles ratio', rate:'Business-use %', saveMin:300, saveMax:900, p:'med' },
      { name:'Safety Gear', note:'Reflective vest, gloves, back brace', rate:'100% deductible', saveMin:50, saveMax:200, p:'med' },
      { name:'Toll Fees', note:'Tolls paid during delivery routes', rate:'100% deductible', saveMin:100, saveMax:500, p:'med' },
      { name:'Parking Fees', note:'Paid parking during deliveries', rate:'100% deductible', saveMin:50, saveMax:300, p:'med' },
      { name:'Car Washes', note:'Keeping delivery vehicle clean', rate:'100% deductible', saveMin:100, saveMax:350, p:'med' },
      { name:'Phone Mount / Accessories', note:'GPS mount, charger for navigation', rate:'100% deductible', saveMin:30, saveMax:150, p:'med' },
    ]
  },
  turo: { title:'Turo Host', sub:'28 deductions available', totalMin:3800, totalMax:9000,
    items:[
      { name:'Depreciation of Vehicle', note:'Rental vehicle depreciated over 5 years', rate:'MACRS depreciation', saveMin:1500, saveMax:5000, p:'high' },
      { name:'Car Insurance (rental %)', note:'Days rented / total days', rate:'Rental-use %', saveMin:400, saveMax:1600, p:'high' },
      { name:'Turo Platform Fee', note:'Turo takes 15“35% of your earnings', rate:'100% deductible', saveMin:500, saveMax:3000, p:'high' },
      { name:'Maintenance & Repairs', note:'Oil changes, tires, brake pads (rental %)', rate:'Rental-use %', saveMin:300, saveMax:1200, p:'high' },
      { name:'Car Washes & Detailing', note:'Between rentals', rate:'100% deductible', saveMin:200, saveMax:800, p:'med' },
      { name:'Roadside Assistance', note:'AAA or similar plan', rate:'Rental-use %', saveMin:50, saveMax:150, p:'med' },
      { name:'Registration & Licensing', note:'Vehicle registration fees', rate:'Rental-use %', saveMin:50, saveMax:200, p:'med' },
      { name:'SE Tax Deduction', note:'50% of self-employment tax', rate:'7.65% of net earnings', saveMin:400, saveMax:1500, p:'high' },
    ]
  },
  youtube: { title:'Twitch / YouTube Creator', sub:'37 deductions available', totalMin:5500, totalMax:14000,
    items:[
      { name:'Camera & Video Equipment', note:'Camera, microphone, lighting, capture card', rate:'100% or depreciated', saveMin:500, saveMax:3000, p:'high' },
      { name:'Home Office / Studio', note:'Dedicated filming/editing space', rate:'$5/sq ft up to 300 sq ft', saveMin:750, saveMax:1500, p:'high' },
      { name:'Internet Bill (business %)', note:'For streaming, uploading, research', rate:'80“100% of bill', saveMin:600, saveMax:1200, p:'high' },
      { name:'SE Tax Deduction', note:'50% of self-employment tax', rate:'7.65% of net earnings', saveMin:800, saveMax:2800, p:'high' },
      { name:'Editing Software', note:'Adobe Premiere, DaVinci Resolve, After Effects', rate:'100% deductible', saveMin:200, saveMax:800, p:'med' },
      { name:'Props & Set Design', note:'Used exclusively for videos', rate:'100% deductible', saveMin:100, saveMax:600, p:'med' },
      { name:'Channel Art & Design', note:'Thumbnails, logos, overlays', rate:'100% deductible', saveMin:100, saveMax:500, p:'med' },
      { name:'Music & Sound Licenses', note:'Licensed music for content', rate:'100% deductible', saveMin:100, saveMax:400, p:'med' },
    ]
  },
  aifreelancer: { title:'AI Freelancer', sub:'31 deductions available', totalMin:5000, totalMax:13000,
    items:[
      { name:'Home Office', note:'Dedicated AI workspace', rate:'$5/sq ft up to 300 sq ft', saveMin:750, saveMax:1500, p:'high' },
      { name:'AI Software Subscriptions', note:'ChatGPT Plus, Claude Pro, Midjourney, etc.', rate:'100% deductible', saveMin:300, saveMax:1200, p:'high' },
      { name:'SE Tax Deduction', note:'50% of self-employment tax', rate:'7.65% of net earnings', saveMin:900, saveMax:3200, p:'high' },
      { name:'Internet (100%)', note:'Essential for AI work', rate:'100% if used exclusively for business', saveMin:600, saveMax:1400, p:'high' },
      { name:'Computer & GPU Equipment', note:'High-performance hardware for AI tasks', rate:'Section 179 or depreciation', saveMin:500, saveMax:3000, p:'high' },
      { name:'Courses & Certifications', note:'AI/ML courses on Coursera, Udemy, etc.', rate:'100% deductible', saveMin:100, saveMax:800, p:'med' },
      { name:'Platform Fees', note:'Upwork, Toptal, Fiverr fees', rate:'100% deductible', saveMin:300, saveMax:1500, p:'med' },
    ]
  },
  rover: { title:'Rover / Wag Dog Walker', sub:'26 deductions available', totalMin:2800, totalMax:7000,
    items:[
      { name:'Business Mileage', note:'Driving to pick up / drop off pets', rate:'70•/mile (IRS 2026)', saveMin:800, saveMax:3000, p:'high' },
      { name:'SE Tax Deduction', note:'50% of self-employment tax', rate:'7.65% of net earnings', saveMin:400, saveMax:1400, p:'high' },
      { name:'Pet Supplies (business use)', note:'Leashes, waste bags, treats for client dogs', rate:'100% deductible', saveMin:100, saveMax:500, p:'high' },
      { name:'Cell Phone Bill', note:'Used for Rover/Wag app and GPS', rate:'50“60% of bill', saveMin:300, saveMax:720, p:'med' },
      { name:'Liability Insurance', note:'Pet sitter / dog walker insurance', rate:'100% deductible', saveMin:150, saveMax:400, p:'med' },
      { name:'Rover / Wag Platform Fee', note:'Platform takes 20“25% of earnings', rate:'100% deductible', saveMin:200, saveMax:800, p:'med' },
    ]
  },
  photo: { title:'Photographer', sub:'39 deductions available', totalMin:5500, totalMax:14000,
    items:[
      { name:'Camera & Lens Equipment', note:'Professional camera bodies, lenses, flashes', rate:'100% or Section 179', saveMin:500, saveMax:4000, p:'high' },
      { name:'Home Studio / Office', note:'Dedicated editing/studio space', rate:'$5/sq ft up to 300 sq ft', saveMin:750, saveMax:1500, p:'high' },
      { name:'SE Tax Deduction', note:'50% of self-employment tax', rate:'7.65% of net earnings', saveMin:800, saveMax:2800, p:'high' },
      { name:'Editing Software', note:'Lightroom, Photoshop, Capture One', rate:'100% deductible', saveMin:200, saveMax:600, p:'high' },
      { name:'Storage (hard drives, cloud)', note:'Backup storage for client photos', rate:'100% deductible', saveMin:100, saveMax:400, p:'med' },
      { name:'Mileage to Shoots', note:'Driving to client locations', rate:'70•/mile', saveMin:200, saveMax:1000, p:'med' },
      { name:'Props & Backgrounds', note:'Backdrops, props used for sessions', rate:'100% deductible', saveMin:100, saveMax:500, p:'med' },
    ]
  },
  taskrabbit: { title:'TaskRabbit Tasker', sub:'27 deductions available', totalMin:3200, totalMax:8000,
    items:[
      { name:'Business Mileage', note:'Driving to and from task locations', rate:'70•/mile (IRS 2026)', saveMin:800, saveMax:3000, p:'high' },
      { name:'SE Tax Deduction', note:'50% of self-employment tax', rate:'7.65% of net earnings', saveMin:500, saveMax:1800, p:'high' },
      { name:'Tools & Equipment', note:'Tools purchased for task work', rate:'100% deductible', saveMin:200, saveMax:1500, p:'high' },
      { name:'Cell Phone (business %)', note:'For TaskRabbit app and client communication', rate:'50“60% of bill', saveMin:300, saveMax:720, p:'med' },
      { name:'Work Clothing / Uniform', note:'Clothing worn exclusively for tasks', rate:'100% deductible', saveMin:50, saveMax:300, p:'med' },
      { name:'TaskRabbit Platform Fee', note:'Platform service fee deducted from earnings', rate:'100% deductible', saveMin:200, saveMax:800, p:'med' },
    ]
  },
};

const savingsData = {
  uber:{est:6400,note:"Mileage, SE tax deduction, phone, insurance"},
  doordash:{est:5800,note:"Mileage, thermal bag, phone, tolls"},
  airbnb:{est:8200,note:"Depreciation, utilities, cleaning, supplies"},
  onlyfans:{est:7100,note:"Equipment, subscriptions, home office, internet"},
  etsy:{est:4900,note:"Materials, shipping, platform fees, packaging"},
  instacart:{est:4200,note:"Mileage, bags, phone, health insurance"},
  freelancer:{est:5600,note:"Home office, software, internet, courses"},
  amazon:{est:4800,note:"Mileage, phone, equipment, safety gear"},
};

// ── NAVIGATION ──
window._showPage = function(page) {
  document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
  document.querySelectorAll('nav a').forEach(a => a.classList.remove('active'));
  document.getElementById('page-' + page).classList.add('active');
  const navEl = document.getElementById('nav-' + page);
  if (navEl) navEl.classList.add('active');
  window.scrollTo(0,0);
}

window._showJobPage = function(jobId) {
  const job = DEDUCTIONS[jobId];
  if (!job) { showPage('jobs'); return; }
  document.getElementById('detailTitle').textContent = job.title;
  document.getElementById('detailSub').textContent = job.sub;
  document.getElementById('detailStats').innerHTML = `
    <div class="ded-stat"><span class="ded-stat-num">${job.items.length}+</span><span class="ded-stat-label">Deductions</span></div>
    <div class="ded-stat"><span class="ded-stat-num">$${job.totalMin.toLocaleString()}</span><span class="ded-stat-label">Min. Savings</span></div>
    <div class="ded-stat"><span class="ded-stat-num">$${job.totalMax.toLocaleString()}</span><span class="ded-stat-label">Max. Savings</span></div>
  `;
  const tbody = document.getElementById('detailTable');
  tbody.innerHTML = job.items.map(item => `
    <tr>
      <td><span class="check-mark">✓</span><span class="ded-name">${item.name}</span><div class="ded-note" style="padding-left:23px">${item.note}</div></td>
      <td>${item.rate}</td>
      <td><span class="save-amt">$${item.saveMin.toLocaleString()} “ $${item.saveMax.toLocaleString()}</span></td>
      <td><span class="priority ${item.p === 'high' ? 'p-high' : 'p-med'}">${item.p === 'high' ? 'High' : 'Medium'}</span></td>
    </tr>
  `).join('');
  document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
  document.getElementById('page-job-detail').classList.add('active');
  window.scrollTo(0,0);
}

// ── BUILD JOB GRIDS ──
function buildGrid(containerId) {
  const container = document.getElementById(containerId);
  if (!container) return;
  container.innerHTML = JOBS.map(job => `
    <a class="job-card" onclick="showJobPage('${job.id}')">
      <div class="job-icon-wrap">
        <svg viewBox="0 0 20 20" fill="none" stroke="#B8924A" stroke-width="1.4">${ICONS[job.icon] || ICONS.user}</svg>
      </div>
      <span class="job-name">${job.name}</span>
      <span class="job-count">${job.count} write-offs</span>
    </a>
  `).join('');
}

// ── CALCULATORS ──
function runCalc() {
  const job = document.getElementById('jobSel').value;
  const income = parseFloat(document.getElementById('incomeIn').value);
  if (!job || !income || income <= 0) { return; }
  const d = savingsData[job];
  const est = Math.round(Math.min(d.est, income * 0.29));
  document.getElementById('resNum').textContent = '$' + est.toLocaleString();
  document.getElementById('resSub').textContent = d.note;
  document.getElementById('resBtn').onclick = () => showJobPage(job);
  document.getElementById('calcRes').classList.add('show');
}

function runFullCalc() {
  const income = parseFloat(document.getElementById('calcIncome').value);
  const stateRate = parseFloat(document.getElementById('calcState').value);
  const job = document.getElementById('calcJobSel').value;
  if (!income || income <= 0) { return; }
  const netSE = income * 0.9235;
  const seTax = Math.round(netSE * 0.153);
  const agi = income - (seTax * 0.5) - 14600;
  const fedTax = Math.round(Math.max(0, agi) * 0.22);
  const stateTax = Math.round(income * stateRate);
  const deductions = job && savingsData[job] ? Math.round(Math.min(savingsData[job].est, income * 0.28)) : Math.round(income * 0.22);
  const quarterly = Math.round((seTax + fedTax + stateTax) / 4);
  document.getElementById('fcSE').textContent = '$' + seTax.toLocaleString();
  document.getElementById('fcFed').textContent = '$' + fedTax.toLocaleString();
  document.getElementById('fcState').textContent = '$' + stateTax.toLocaleString();
  document.getElementById('fcDed').textContent = '$' + deductions.toLocaleString();
  document.getElementById('fcQuarterly').textContent = '$' + quarterly.toLocaleString();
  document.getElementById('fullCalcResult').style.display = 'block';
}

// ── INIT ──
buildGrid('homeJobGrid');
buildGrid('allJobGrid');